name: huiwenchen
favicon: null
layout_spectrum: 0.5454890176188201
typography_spectrum: 0.8747523508500308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2870886118616909
  lightness: 0.03586570615880191
  saturation: 0.31610129680484533
  rhythmicContrast: 0.12493226421065629
purpose: []
