name: huiwenchen
favicon: null
layout_spectrum: 0.78248
typography_spectrum: 0.8747523508500308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2c2c'
    - '#ffffff'
    - '#a9a9a9'
    - '#686767'
    - '#898888'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
